language: r
cache: packages
r:
- oldrel
- release
- devel
after_success:
- test $TRAVIS_R_VERSION_STRING = "release" && Rscript -e 'covr::codecov()'
- bash pkgdown.sh
env:
  global:
    secure: EZl7hBBDN3zkIRWhV+ARFv4LIfVCMM+OrXMkPdTkKyLDYXNYhsUXtEP7c5p8HfykIKHZzgIcktUwOhcZJgGV4N2NfK+DXCaL+5YCTORF8uhYj4bCyQ2p55Pyf1wqquqILoqiGHNGQINi9PhtD8eW6HeAjQ57aPZEjyykmMWaiIkRdGNDGmXQAWNMR+MQiHuDoQwkL4XriK+KNX/B7YfHVuHoAxJRZED63dxZClOYOWN0cpO7muD9rQC1f0aAQ6UdsKAtGuPzbIOGg4YG0baqV3goWWn9rZwNqMr05e1BBr0CrVSaJcE6eO/1e2aXHNFE2xth7YTsYP4h4tHS9O8klSZKUWugN3/O+G3Tpznv3Kn14oDo1ll5Hd07j2Wkkr0A9YHvEKsQi7IYhgCUg3JY3qh4h+Rt0oDFimqO2Og0vs1svL0YGoihR1JKRSNkpnURBptmXVqie87/IgpjLlMS2IhlG6ZFQvpTFzfQm08epR7B0E6ZG7TppZGeN/vycEBZhyxpZMY3TmHNPFLXNWzyPOlH7Oxlc/bgoW6c3M+m6ROQfoQBlgHO3K9AYqK/fQT65lBLDJPM3ZShKKka28dIt7OzOADtEKCXbz2IJDYu9NFIhkNLV0J3KxKhZvDH83chFRYNrDd17c74HylOBtwASilpPxTFljDtKmml52uF0II=
