---
title: "Including Static Dashboards in Crunch"
description: "How to include Flexdashboards in a Shiny App"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Static Dashboards}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Crunch allows you to host Shiny apps on the Crunch Jupyter server. Shiny apps are great, but they can be difficult to program, and can be very slow if not designed properly. [Flexdashboards](https://rmarkdown.rstudio.com/flexdashboard/) provide an easy-to-use alternative to Shiny apps. Instead of re-rendering dynamically based on the user action, Flexdashboards are effectively static websites which only include data which is live at the time of rendering. This can be desirable both because they are much easier to write, and because you can test and validate the dashboard's behavior before it goes to the client. Additionally, since you have finer control over when a dashboard is rendered, you can include more computationally expensive operations like fitting a machine learning model without affecting user experience.

You can host Flexdashboards on Crunch's Shiny infrastructure using Shiny's `includeHTML` function. What `includeHTML` does is add an HTML file to the shiny UI. If all you include in the shiny UI is the Flexdashboard html file, then the Shiny app effectively becomes a static site. 

### Basic workflow
Follow these steps to include a Flexdashboard in your Shiny app: 
1) First create a new Rmarkdown document with a Flexdashboard output option. 
1) Render the Rmd file into an html file
1) Uploaded the rendered html file to your app's Jupyter folder
1) In your shiny UI code add `includeHTML(<filename>)` to the `ui` object. Your `app.R` file might look something like this:

```
library(crunchy)
ui <- fluidPage(
    includeHTML("dashboard")
)

server <- function(input, output, session) {}

# Run the application 
shinyApp(ui = ui, server = server)
```
Note that we haven't included any authentication in this app which means that users who do not have access to a dataset could theoretically access it. The next step is to check that the user is logged into Crunch. 

### Check User Authentication

Crunchy includes a `shinyUser()` function which lets us display different content to the user depending on whether they are logged into Crunch of not. To do this we'll make use of Shiny's `renderUI` function to conditionally create a different UI for different types of users.

```
ui <- fluidPage(
    uiOutput("dashboard")
)
```

This creates the UI object, but most of the work is going to be done on the server side. We can use the `shinyUser()` function to get a user record for the current viewer of the app. This record includes some useful pieces of information, including the user's name, their email address, and their Crunch preferences. You can use this object to conditionally display different dashboards for different users like so: 

```
server <- function(input, output, session) {
    user <- shinyUser()
    output$dashboard <- renderUI({
        if (is.character(email(user()))) {
            includeHTML("acme_dashboard.html")
        } else {
        h1("You are not logged in, please visit app.crunch.io to login")
        }
    })
}
```

This prevents unauthorized users from seeing the rendered dashboard, and directs them to the crunch website which will refresh their authentication cookie. 

### Conditional dashboards and user identification

We can take this pattern one step further to show different users different dashboards. We use the same UI object, but check the user's email and change the displayed HTML file based on that email. 

```
server <- function(input, output, session) {
    user <- shinyUser()
    output$dashboard <- renderUI({
        if (is.character(user())) {
            h1(user())
        } else if (grepl("acme.com$", email(user()))) {
            includeHTML("acme_dashboard.html")
        } else if (grepl("globex.com$", email(user()))) {
            includeHTML("globex_dashboard.html")
        } else {
            h1("You are not logged in, please visit app.crunch.io to login")
        }
    })
}
```
What this does is check the user's email address to identify clients from one company, and then displays a rendered dashboard for that company. If they are not logged into Crunch, they will get a message instructing them to log in. An example app of this kind is  [here](https://github.com/Crunch-io/crunchy/tree/master/inst/example_apps/rmd_dashboard_app), to run it, copy the app folder, open `app.R` and run it with `shiny::runApp("app.R"), or by clicking the "Run App" button in RStudio. 

### Managing Dashboard Renders

The above code assumes that you are going to be re-rendering your Rmd files manually, and uploading the results to the Jupyter server. You can also re-render the Rmd files dynamically as part of the Shiny app by calling `rmarkdown::render()` somewhere in your server function. For example the following app re-renders the dashboard whenever the user clicks an action button. Note that for this to work smoothly you should use the [reactivePoll](https://shiny.rstudio.com/reference/shiny/1.0.2/reactivePoll.html) to ensure that the UI is refreshed after the file is regenerated. If you don't use `reactivePoll` you might end up in a situation where the UI refreshes before the RMarkdown file is finished rendering. 

```
library(crunchy)

ui <- sidebarLayout(
         sidebarPanel(
             actionButton('refresh', 'Refresh Dashboard'),
             textOutput("last_render")
         ),
    mainPanel(
             uiOutput("dashboard")
    )
)

server <- function(input, output, session) {
    file <- reactivePoll(1000, session,
        checkFunc = function() {
            file.info("acme_dashboard.html")$ctime
            }, 
        valueFunc = function() {
            list(path = "acme_dashboard.html",
                time = Sys.time()
                )
            })
    observeEvent(input$refresh, rmarkdown::render("acme_dashboard.Rmd"))
    output$last_render <- renderText(paste("Last Render:", file()$time))
    output$dashboard <- renderUI({
        if (inherits(shinyUser(), "UserEntity")){
            includeHTML(file()$path)
        }
    })
}

shinyApp(ui = ui, server = server)
```

A full example can be found [on Github](https://github.com/Crunch-io/crunchy/tree/master/inst/example_apps/dynamic_render_app)

### Conclusion

Flexdashboards provide a simple way to communicate with your users. By using the Crunch Shiny infrastructure you can host and distribute static dashboards in the same way as Shiny apps. This allows you to customize the behavior Crunch Dashboards without needing to worry about some of the complexity which comes along with Shiny apps. 