app <- ShinyDriver$new("../")
app$snapshotInit("mytest")

app$setInputs(search = "G")
app$setInputs(selected_vars = "Gender")
app$snapshot()
app$setInputs(search = "")
app$snapshot()
app$setInputs(selected_vars = c("Gender", "Categorical Location"))
app$snapshot()
app$setInputs(search = "C")
app$setInputs(clear_all = "click")
app$snapshot()
app$setInputs(search = "")
app$snapshot()
